import localFont from "next/font/local";
import "./globals.css"; // Importing global styles
import Navbar from "@/components/Navbar/Navbar"; // Importing Navbar component
import Footer from "@/components/Footer/Footer"; // Importing Footer component

// Uncomment these lines if you want to use custom fonts
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App", // Title for the document
  description: "Generated by create next app", // Description for SEO
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // If you are using custom fonts, uncomment the next line
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />  {/* Renders the Navbar component */}

        <Footer />  {/* Renders the Footer component */}
      </body>
    </html>
  );
}
